# Generated by Django 5.0.3 on 2024-03-20 16:09

import MyMusicApp.base.validators.minlenvaluevalidator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[MyMusicApp.base.validators.minlenvaluevalidator.minlenvaluevalidator]),
        ),
    ]
